# Generated by Django 3.2.14 on 2022-07-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secusigne', '0002_auto_20220714_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products_images')),
                ('slug', models.SlugField(max_length=200)),
                ('detail', models.TextField()),
                ('specs', models.TextField()),
                ('price', models.PositiveBigIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secusigne.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secusigne.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secusigne.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secusigne.size')),
            ],
        ),
    ]
